baseurl: https://pat-alt.github.io/
languageCode: en-us
title: Patrick Altmeyer
theme: "hugo-lithium"
publishDir: "pat-alt.github.io"
googleAnalytics: ''
disqusShortname: 'patrickaltmeyer'
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: Blog
      url: /
    - name: GitHub
      url: https://github.com/pat-alt
    - name: CV
      url: /resume
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A collection of ideas, notes and code.
  avatar: avatar.png
  menu_item_separator: "-"
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: avatar.png
    width: 50
