baseurl: https://pat-alt.github.io/
languageCode: en-us
title: Patrick Altmeyer
theme: "hugo-lithium"
publishDir: "pat-alt.github.io"
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
      weight: 1
    - name: Blog
      url: /
      weight: 1
    - name: CV
      url: /resume
      weight: 3
    - name: Tags
      url: /tags/
      weight: 2
    - name: Categories
      url: /categories/
      weight: 2
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A collection of ideas, notes and code.
  avatar: avatar.png
  menu_item_separator: "-"
  favicon: logo_icon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
  footer: "&copy; [Patrick Altmeyer](https://pat-alt.github.io/) 2021- | [Github](https://github.com/pat-alt) | [LinkedIn](https://www.linkedin.com/in/patrick-altmeyer-a2a25494/) | [From Scratch](https://pat-alt.github.io/fromScratch/)"
