---
title: "Resume"
author: Patrick Altmeyer
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
---

Last updated on `r Sys.Date()`. For a more detailed printable version click [here](/pdf/curriculum_vitae.pdf).

## Contact Info {#contact}

- altmeyerpat@gmail.com
- [GitHub](https://github.com/pat-alt)
- [LinkedIn](https://www.linkedin.com/in/patrick-altmeyer-a2a25494/)

## Education {#edu}

### MSc Data Science

Barcelona Graduate School of Economics (2020-2021)

### MSc Finance

Barcelona Graduate School of Economics (2017-2018)

Thesis: [Option Pricing in the Heston Stochastic Volatility Model: An Empirical Evaluation](https://thevoice.barcelonagse.eu/2018/10/30/option-pricing-heston-stochastic-volatility-model-empirical-evaluation/)

### MA Economics

University of Edinburgh (2013-2017)

Thesis: [Can misguided monetary policy explain the European housing bubble?](https://thevoice.barcelonagse.eu/2017/09/12/can-misguided-monetary-policy-explain-the-european-housing-bubble/)

## Research Experience 

### Research Hub Secondee

Bank of England (2018-2020)

- Co-author of two staff working papers (upcoming) both of which involved high-
dimensional data sets and drew heavily on my computational skills: PCA, k-means and
hierarchical clustering, LASSO, quantile regression.

## Professional Experience {#prof}

### Economist

Bank of England (2018-2020)

- Initiated and led the development of a large-scale, modularized and packaged R Shiny app now used for automated data access, transformation and visualisation in the Bank.
- Briefing work for policy committees including analysis, presentations and speaking
notes for senior management and Markets’ Deputy Governor Sir Dave Ramsden.

## Teaching Experience {#teach}

### Lead Trainer -- R and git

Bank of England (2018-2020)

- Introduced colleagues to R programming and git version control on voluntary basis through several organized training sessions that formed part of an ongoing project to enable staff in the fields of programming and data science.

### Teaching Assistant for Econometrics

School of Economics -- University of Edinburgh (2017)

- Helped students to get familiarised with applications of econometrics in Stata during
computing labs.
- Actively taught econometrics in tutorials jointly with senior teaching fellow.
- Supported students with issues during office hours

## Conferences {#conf}

### Money markets and central bank balance sheets

[European Central Bank workshop](https://www.ecb.europa.eu/pub/conferences/html/20191111_ecb_money_market_workshop_conference.en.html) (2019)

- Presented our draft staff working paper on modelling the demand for central bank reserves together with my co-author and supervisor Rafael Kinston.

## Programming & Software {#prog}

**Languages**: Python, R, SQL, MATLAB, C++, Stata, bash/zsh, HTML, Markdown, CSS, LaTeX

**Technologies**: git, Docker, Postgres, AWS, R Shiny

**Relevant software**: R Studio, Atom, Datastream, Bloomberg Terminal, MS Office

## Languages {#lang}

German (Native), English (Fluent), Spanish (Proficient)

## Outreach and awards {#awards}

- 3rd Prize Winner of [Novartis Datathon](https://godatathon.com/). (2020)
- Full funding for MSc Data Science awarded jointly by Bank of England and BGSE. (2020)
- Barcelona GSE total tuition fee waiver for MSc Finance. Awarded based on academic merit. (2017)
- Edinburgh University School of Economics Joint Prize for the best performance in Economics. (2017)
- Held a [TEDx talk](https://www.youtube.com/watch?v=b8qpLOMGYT0) about European Integration, Diversity and Societal Well-being. (2016)
- School of Economics Prize for academic excellence in Economics. (2014)
